### ISSUE TITLE
Cloud installation (4.4.6.2.1.3)

### ISSUE THREAD

**Issue by dev10** [offscale/offsetup-rfc#6]
* Do we wish to support any cloud as long as it implements a common interface?
* Are we going for full automation (provisioning nodes etc on Docker or cloud provider) and setting up the applications?

**Comment by SamuelMarks** [comment]
`offsetup` shouldn't be cloud-aware. That's for other components. The main thing is that the builds are idempotent, so snapshots are workable:
https://github.com/offscale/offscale-rfcs/blob/master/[offregister]%20Binary%20(Rust%3F)%20reimplementation.md

---

Cloud interface will be provided by other Offscale components, like [offstrategy](https://github.com/offscale/offstrategy) and [offregister](https://github.com/offscale/offregister). These two are currently in Python, and the current choice is between writing them in Rust, Go, or using Hashicorp or Brooklyn in its stead.
